### ISSUE TITLE
42mins[TEST] 看看这个仓库是不是公开的, 可供怼圈外人士交流

### ISSUE THREAD

**Issue by liguanghe** [DebugUself/debuguself.github.io#1]
如题
- 怼圈常用的仓库是私人的, 但怼圈需要跟外界交流, 考虑了一下, 这个公开博客的仓库平时不需要 issue 沟通, 又是公开的, 所以就用这个仓库的 issue 来完成教留的目的.

**Comment by ZoomQuiet** [comment]
DONE as good! 达成/归档/交付ed
