### ISSUE TITLE
42h[TASK]20180708深圳开智 * 自怼圈分享及纪要

### ISSUE THREAD

**Issue by liguanghe** [DebugUself/debuguself.github.io#2]
## 时间地点
- 时间: 20180708 10:30 - 18:30
- 地点: 深圳大学城 流霞的茶
- 人物: 开智部落 * 开智课程 * 自怼圈

## 资源
- 视频: (稍后补)

## 请大家把纪要留言在这个 issue 下面~
内容包括但不限于:
- 自我介绍
- 自己今天分享的内容
- 其他人的分享中给你印象最深的点
- 下一步行动

**Comment by liguanghe** [comment]
[和深圳的伙伴们喝茶 | Li Guanghe's blog](https://liguanghe.github.io/2018/07/08/MeetSZ20180708/)

**Comment by tanchangde** [comment]
# 自我介绍

一个不想成为信息黑客的阅读者不是好文科男。

# 分享内容：我的后开智时光——卡片大法消化老阳博客

16 本科毕业两年，换了东家。从物流跨行互联网金融，从执行者转变为摸索者。全新的业务，全新的工作流都需要我快速学习。那时恰逢情感困惑，茫然四顾找不到对话的人。偶然逛到阳老师博客，发觉他的文章和以往看过的完全不一样。不但结合了切身体验而且旁征博引，证据鲜活。结合自己经历一对照，不禁点头如捣蒜——阳老师看问题实在透彻。我如饥似渴、囫囵吞枣的看了大几十篇，却脑子发涨，因为信息密度太大了。就埋头工作去了，但阳老师仍然在我脑海里牛逼闪闪发着光，不曾暗淡。

之后在工作上吃过了点亏，走了一些弯路。再看阳老师的文章，不禁懊悔当初没看进去。所以我就琢磨着换个法子重新看。这一次我用上了幕布。幕布是在寻找 workflow 替代品时发现的。简而言之，幕布主要用来把信息点组织成有层级的清单。然而，这一次消化阳老师的东西又闹了肚子。因为这种整理信息单元太大，不过是关键信息的摘录，别人的还是别人的。还不如直接保存文章呢。另外这种整理本身很费劲，看不到应用场景。没有甜头的事情注定被天生嗜甜的人类抛弃。我就像一只饿瘪肚子的小老鼠掉进了阳老师的大米缸，心很大奈何消化能力有限。只能绕着米缸转圈徒呼奈何。

17-18 年，我就这么在阳老师的大米缸里逛着，这里刨一刨，那里啃一啃。写作课吴期结束的某一天，我留意到阳老师在《笨办法学语言》及编程学习中均提到：可以用 Anki 这样的间隔重复软件记忆难以掌握的知识点。是不是也可以用 Anki 消化阳老师博客里的行动以及高阶模型呢？试试看！饱受后知后觉之苦，动手琢磨尘封已久的 Anki。学习一个工具，最好的办法是先看官方文档。我看了 Anki 中文社区翻译的中文版文档基础术语部分（翻译糟糕，以至于我自己动手翻译了一版），主题了解 Anki 时，了解了“学习骇客”博客介绍的 Anki 学习方案设置。利用简书博主介绍的超高人气插件 Power Format Pack，在 Anki 中实现 Markdown 语法编辑。选了阳老师博客几篇文章做尝试，按软件提示复习卡片，并结合自己新体验反复消化。

一次月度深圳线下伙伴聚会，突然发现自己可以针对伙伴发言迅速给到阳老师提到的一些点！原来这样消化阳老师博文是行得通的～阳老师这个大米缸，我可算吃上了。

# 下一步行动

每天 Anki 化一篇阳老师博文～

# 其他人的分享中给我印象最深的点

广鹤分享的时间记录以自怼的方法真是让我既怕又爱。这确实是一个直面不堪自我的好方法，尤其是对于自我觉察意识不强的人。
