### ISSUE TITLE
28d[ASK] 如何增加组织内个人的科研素养？

### ISSUE THREAD

**Issue by Hugo1030** [DebugUself/debuguself.github.io#7]
## 问题
- 如何增加同事的科研素养？什么样的活动形式能让个人养成阅读论文的习惯？（像怼圈？）

## 背景
- 公号组希望公号文章更科学，想通过培养每个同事阅读论文的习惯，增加写作中论文引用的频率；
- 内容组有一半同事（4人）非心理学专业；
- 工具使用：github --简单网页上传文章/发issue；

## 目标和计划

- 目标：文章增加最新论文的引用；增强同事的科研素养；
- 历史尝试：让心理学专业的同事每周做主题分享；时间半小时；历时半年；
- 结果失败：没有让非心理学专业同事参与进去，没有应用到实际文章中；听了就忘，效果不佳。
- 新计划：让同事每周上传一篇论文摘要，条件是 1. 与6岁以下儿童相关；   2. 能跟父母关心的育儿话题结合； 
- 工具：Github - issue，统一到issue [科研选题] 下。

## 现象

计划实施一周，发现如下问题：

- 有多半同事不提交；
- 已提交的，多属应付，无法给出正反 / 古今的论据验证；
- 想认真做的，有难度：要求提交一篇论文， 实际要搞清楚论文主题背后的真伪/历史，相当于写一篇小论文,对非心理学专业同事负担不小。
- 没讨论/没交流：因为任何交流都得建立在了解的基础上，而想了解， 除非仔细看对方提供的论文以及相关背景资料；
- 工具太正式，一般同事没有用 issue 交流问题的习惯，不愿意登入 github； 

预计：两周后没人再提交issue。

## 分析
分析原因有三：

### 1. 没有和切身利益结合
公号的 KPI 是： 阅读量/留言率/点赞率/分享率，没有科研论文的引用， 也能达标；
 
科研论文的引用是为了长远的正向循环和公司品牌的建立；但目标太远，现实很近；

### 2. 没有真正闭环
组会分享和对外发布都算闭环，但我们通常只扔一个 论文链接 + 摘要， 并没有形成真正的闭环；

### 3. 没有反馈
同事没有时间看对方的论文主题，不能形成讨论，最多是提问；

## 方案

依上分析，我想有下面几点可以改进：

### 针对 1. 的解决思路：
   和本周自己的原创文章结合：要求文章里必须有最新论文引入； 即使没引入， 也要补上当周组会或下周组会分享；

   可能遇到的困难是：

   - 撰写原创文章的只有三位，其他同事怎么办?(其他同事都是心理学的，可以不考虑)
   - 写文章已经很花时间很难了，有无精力做此事？且找论文是无底洞，特别影响效率；

### 针对 2. 的解决思路：

多增加一个分享环节：模仿怼圈周六例会

- 另开时间专门做论文分享：每人 10 分钟，其他提问答疑 3 分钟；

可能遇到的困难是： 

- 提问答疑造成问题发散，无法控制时间，后面的人无法分享；
- 多个主题，无法做会前充分准备；
- 没有一个有分量回怼的人，这是最大的困难；

### 针对 3.的解决思路
没有时间的本质是对这件事不熟悉，没有入门，需要花大量的时间和精力学习看论文的方法/学习背景知识等等，宁愿做熟悉的事情。

如何解决：

- 硬着头皮上；
- 读如何读论文的书；
- 只找和此次主题相关的论文(经测验，这也是有下限无上限的事情)；
- 补充认知心理等背景科目；

可能遇到的困难：

- 难以坚持，困难太大；

以上，问题描述完毕。请大妈 @ZoomQuiet  和 大家看看哪种可行? 那种更易成功? 或有其它思路建议？

**Comment by ghost** [comment]
作为一个基本不读论文的发个言，倾向于2，但是每次限定固定一篇论文，大家一起看，有人讲解怎么读论文（貌似写论文是有套路的，读论文是否也类似，比如读读开头结尾就可以了，大大缩短读论文时间？）。每次分享的论文涉及不同的心理学概念，懂的人来讲解。慢慢培养习惯。

找论文也是个头大的事情，是否有专人事先找好，再大家去读。。。

**Comment by ZoomQuiet** [comment]
@Hugo1030 是也乎,(￣▽￣)

> 没有动力

- 这才是一切的根源哪
- 论文和当前工作/任务如何关联起来?
    + 如果你能证明, 论文引用能极大的提高公号订阅量
    + 否则, 是根本无人愿意嗯哼的...
- 所以,方法有3+
    + 硬怼, 要到政策, 带大家看论文, 先解决看论文的姿势, 然后再引导输出
    + 反撅, 根本不提论文这事儿, 要到公号统计接口, 自己开始持续的论文摘要之类高品质内容输出
        * 积累一定数量后
        * 证明, 论文摘要/理解/广泛阅读, 对公号/个人能力...
        * 有非常大的推动
        * 大家自然会来跟上
    + 别途, 放弃没有动力的同事, 招收有论文阅读习惯的新人, 形成强烈对比的团队
        * 自然有后续...
        * 甚至于, 变成年度奖金评比标准

**Comment by NBR-hugh** [comment]
补充一些看法

> 文章增加最新论文的引用；增强同事的科研素养；

看论文是手段,不是目的,所以这个目标不好,高深的学术内容从来是传播的敌人,为了引用而引用容易本末倒置
所以建议抛弃前一个目标,保留后一个目标: 增强同事的科研素养,即先养成共读的习惯再说

如果从短期入手,提高文章的质量,那么是可以直接考虑配合与共创: 人是最强的信息源. 既然身边有熟读论文的专业的同事,那么主题的确定的情况下是否可以直接请教有什么实验或者论据支持与反对? 从而写作的同事专心在表现的形式上: 如何写得更有趣,更吸引人? 然后双方在讨论与合作中互相促进?  

因此文章的质量提升与人学术素养提升建议分开考虑,不应混杂.

> 没有让非心理学专业同事参与进去，没有应用到实际文章中；听了就忘，效果不佳。

从养成习惯到理解,到真正应用时需要时间,想要一撮而就是不可能的,所以建议应用到实际文章上应用先抛一边,先考虑如何让人们参与进来,然后再考虑如何做得更好.一个阶段一个阶段来.

时间上: 参与(固定时间节奏与成果) -> 精彩(从活动中感受到收益) -> 共创(大家一起来想怎么做的更好,从形式到内容)

形式上我建议以研讨会或辩论会的形式来互动起来: 

- 一个人写一篇很难,那能不能一起写一篇? 
- 找论文很麻烦,那能否把广度搜索与深度研习分开练习?
- 直接去读论文很难,那是否可以先抛出自己的想法观点,然后与论文进行碰撞,与其他人的想法碰撞,然后自己的认知得以更新. 这种豁然开朗对我而言是最大愉悦,也是最强的推动力.

**Comment by QiLinJane** [comment]
@ZoomQuiet 
> * 如果你能证明, 论文引用能极大的提高公号订阅量

公号上还不能证明论文的作用，但「得到」「家庭育儿宝典」的十万用户有口皆碑，既兼顾科研又兼顾育儿方法，是不错的标杆。但无法排除得到平台、知识大咖的影响，说服力不够。

不过 引导大家向此看齐，还是可以的。（算是历史证明）

我也认为这是关键的关键。





> * 硬怼, 要到政策, 带大家看论文, 先解决看论文的姿势, 然后再引导输出

上午的确要到了政策，给同事先做了 zotero/rss订阅的工具培训，先解决了工具姿势；

接下来几周会带同事解决看论文姿势。

输出的话：鼓励发个人微博，公号等等一切能放大自己品牌效应的地方。


> * 反撅, 根本不提论文这事儿, 要到公号统计接口, 自己开始持续的论文摘要之类高品质内容输出

我自己做得不够好，但有好的同事已经做到了：2 h迅速初稿，含科研论文，当日一万加；非常鼓舞人，可惜这样的例子很少，半年只有一粒；

后续如何继续输出这样的文章，有两个侧向

1. 「选题会」要给这样的选题腾出空间，不能全部跟着热点和节假日来
2. 用数据说话：把得到文章按「年龄」「最多」划分历史文章，找出每个年龄家长最关心的问题，根据这些问题提炼知识点撰写文章，会更精准。解决「科研」「育儿问题」割裂的难题




这一点还需要领导们配合，kpi 不能只认阅读量。
上午也沟通过了；



> * 放弃没有动力的同事, 招收有论文阅读习惯的新人, 形成强烈对比的团队

这一点的确很残酷，但历史证明很有效，类比：「一部分人先富起来」



> * 甚至于, 变成年度奖金评比标准

虽然这一部分自己做不了主，但可以影响内容这边的KPI 加入「科研」这一项。

---

目前最关键的现状是：非心理学专业的主笔，不用论文也是篇篇 7000+（对比我们的文章一般是 4000-6000）

**Comment by QiLinJane** [comment]
@Vwan 
> 找论文也是个头大的事情，是否有专人事先找好，再大家去读
- 还真有同事每周整理论文，只不过之前同事从来不看；
- 本周打算启用




> 读论文是否也类似，比如读读开头结尾就可以了，大大缩短读论文时间

理论上可以，但要看是什么目的；

- 如果只是刷论文，这样足够；
- 如果要根据主题写论文，一定要读里面的方法和测量，方法是关键；这是难的地方
- 还有最难的：反方观点和论据；


亲身经历：依靠自己查资料写一篇文章，论文就要读3-4天；（我还没找到更省力的方法）







> 慢慢培养习惯

我也在想这件事情，习惯如何培养既慢慢又能绵延不绝不断掉？
- 我观察编程圈子，得出一点结论是：生态圈；有无全世界关注儿童心理学的大池子？

**Comment by QiLinJane** [comment]
> 貌似写论文是有套路的，读论文是否也类似，比如读读开头结尾就可以了，大大缩短读论文时间？

有：[会读才会写 (豆瓣)](https://book.douban.com/subject/26655043/) 必看

**Comment by QiLinJane** [comment]
> 一个人写一篇很难,那能不能一起写一篇?

不能：实践过；一开始一个写手配一个科研助手，证明完全不可用；文章的单位是文章，再粗劣也是完整的文章；不是片段，不是科研素材；（后续有机会我会讲讲为什么不可行）

> 找论文很麻烦,那能否把广度搜索与深度研习分开练习?

不存在「练习」的说法；不太清楚广度搜索，一般是就某个主题搜索：比如 father  involed

> 直接去读论文很难,那是否可以先抛出自己的想法观点,然后与论文进行碰撞,与其他人的想法碰撞,然后自己的认知得以更新. 这种豁然开朗对我而言是最大愉悦,也是最强的推动力


目前是这样：当我们想用一个有利于我观点表达的论据时候，会请科研助理帮忙查一下有无类似证据；也就是先观点，后论据；
